"""empty message

Revision ID: 4b436a2f276a
Revises: 29675d7edc59
Create Date: 2015-08-03 20:45:42.848157

"""

# revision identifiers, used by Alembic.
revision = '4b436a2f276a'
down_revision = '29675d7edc59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=True),
    sa.Column('l_name', sa.String(), nullable=True),
    sa.Column('favorite_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
